- name: Hardware
  hosts: raspberry
  become: true

  vars:
    tas5805m_repo: https://github.com/sonocotta/tas5805m-driver-for-raspbian
    tas5805m_dest: /src/tas5805m-driver-for-raspbian
    tas5805m_i2c_address: "0x2d"

  tasks:
  - name: Get kernel architecture
    shell: uname -m
    register: kernel_arch
    changed_when: false

  - name: Set kernel headers package based on architecture
    set_fact:
      kernel_headers_package: "{{ 'linux-headers-rpi-v8' if kernel_arch.stdout in ['aarch64', 'arm64'] else 'linux-headers-rpi-v7' if kernel_arch.stdout == 'armv7l' else 'linux-headers-rpi-v6' }}"

  - name: apt install packages
    apt:
      name: 
      - git 
      - "{{ kernel_headers_package }}"
      - build-essential
      state: present

  - name: Git checkout tas5805m kernel module from github
    ansible.builtin.git:
      repo: "{{ tas5805m_repo }}"
      dest: "{{ tas5805m_dest }}"

  - name: Build kernel module
    run_once: true
    ansible.builtin.shell: make all
    args:
      chdir: "{{ tas5805m_dest }}"

  - name: Install kernel module
    run_once: true
    ansible.builtin.shell: make install
    args:
      chdir: "{{ tas5805m_dest }}"

  - name: Compile DT overlay
    run_once: true
    ansible.builtin.shell: ./compile-overlay.sh
    args:
      chdir: "{{ tas5805m_dest }}"

  - name: Patch config.txt
    lineinfile:
      dest: "{{ config_path }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
    - { regexp: '^dtoverlay=w5500', line: 'dtoverlay=w5500' }
    - { regexp: '^dtoverlay=tas5805m', line: 'dtoverlay=tas5805m,i2creg={{ tas5805m_i2c_address }}' }

  # Disable HDMI audio output
  - name: Disable HDMI audio
    replace:
      dest: "{{ config_path }}"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.line }}"
    loop:
    - { regexp: '^dtparam=audio=on', line: '#dtparam=audio=on' }
    - { regexp: '^dtoverlay=vc4-kms-v3d', line: '#dtoverlay=vc4-kms-v3d' }


  # Requires reboot due to hardaware configuration changes
  - name: Reboot the machine (Wait for 5 min)
    reboot:
      reboot_timeout: 300