raspberry:
    hosts:
        # arm-v6 device
        # raspberry-pi-hifi-01:
        #     ansible_host: 192.168.1.50 
        #     raspi_pkg: https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb
        # raspberry-pi-loud-01:
        #    ansible_host: 192.168.1.233
        #    ansible_user: dronische
        #    raspi_pkg: https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb
        rpi-pulse-1:
           ansible_host: 192.168.1.85
           ansible_user: dronische
           raspi_pkg: https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb

        # arm-v7 device
        # raspberry-pi-hifi-02:
        #     ansible_host: 192.168.1.51 

    vars:
        ansible_user: pi
        ansible_ssh_pass: raspberry
        kernel_header_package: raspberrypi-kernel-headers
        raspi_pkg: https://dtcooper.github.io/raspotify/raspotify-latest_armhf.deb
        config_path: /boot/firmware/config.txt

orangepi:
    # these uses ssh key (passwordless) auth passed via
    # ssh-copy-id dronische@192.168.1.54
    hosts:
        # loud-orangepi-01:
        #     ansible_host: 192.168.1.54
        #     ansible_user: dronische
        # orange-one-02:
        #     ansible_host: 10.42.0.141
        #     ansible_user: pi
    vars:
        kernel_header_package: linux-headers-current-sunxi
        raspi_pkg: https://dtcooper.github.io/raspotify/raspotify-latest_armhf.deb
        config_path: /boot/armbianEnv.txt