raspberry:
    hosts:
        # arm-v6 device
        # raspberry-pi-hifi-01:
        #     ansible_host: 192.168.1.50 
        #     raspi_pkg: https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb
        #     config_path: /boot/config.txt
        # raspberry-pi-loud-01:
        #    ansible_host: 192.168.1.233
        #    ansible_user: dronische
        #    raspi_pkg: https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb
        # rpi-pulse-1:
        #    ansible_host: 192.168.1.85
        #    ansible_user: dronische
        #    raspi_pkg: https://github.com/dtcooper/raspotify/releases/download/0.31.8.1/raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf.deb
        # arm-v7 device
        # raspberry-pi-hifi-02:
        #     ansible_host: 192.168.1.206 
        #     arch: armv7
        # pi-pulse-3:
        #     ansible_host: 192.168.1.49
        #     arch: armv7
        lab-raspi4:
            ansible_host: 192.168.1.12
            arch: armv7
            # display_oled_dual: true
            display_tft_dual: true
        # amped-raspi-2:
        #     ansible_host: 192.168.1.127
        #     arch: armv6
        #     display_oled_single: true
        # amped-raspi:
        #     ansible_host: 192.168.1.244
        #     arch: armv6
    vars:
        ansible_user: pi
        #  if you're not using ssh-key auth, provide password below
        # ansible_ssh_pass: raspberry
        kernel_header_package: raspberrypi-kernel-headers
        raspi_pkg: https://dtcooper.github.io/raspotify/raspotify-latest_armhf.deb
        config_path: /boot/firmware/config.txt