- name: install librespot
  hosts: orangepi
  become: true
  
  tasks:
  - name: apt install packages
    when: "'orangepi' in group_names"
    apt:
      name: 
        - libc6 
        - coreutils 
        - systemd 
        - init-system-helpers 
        - libasound2 
        - alsa-utils 
        - libpulse0
      state: present

  - name: Download raspotify
    get_url: 
      url="{{ raspi_pkg }}"
      dest="/tmp/raspotify-latest_armhf.deb"

  - name: Install raspotify on orangepi
    run_once: true
    ansible.builtin.shell:
      cmd: "dpkg --ignore-depends=coreutils --ignore-depends=alsa-utils --ignore-depends=systemd --ignore-depends=init-system-helpers --ignore-depends=libasound2 -i /tmp/raspotify-latest_armhf.deb"
