- name: install gmediarender
  hosts: raspberry
  become: true
  
  tasks:
  - name: apt install packages
    apt:
      name: 
        - gmediarender 
        - gstreamer1.0-plugins-base 
        - gstreamer1.0-plugins-good 
        - gstreamer1.0-plugins-ugly 
        - gstreamer1.0-pulseaudio
      state: present

  - name: gmediarender system service
    copy:
      dest: "/etc/systemd/system/gmediarender.service"
      content: |
        [Unit]
        Description=gmediarender UPnP Renderer

        [Service]
        Type=simple
        EnvironmentFile=/etc/default/gmediarender
        ExecStart=/usr/bin/gmediarender --friendly-name raspberry --logfile=stdout --port 49494
        Restart=on-failure
        User=nobody
        Group=audio

        [Install]
        WantedBy=multi-user.target
  
  - name: Start gmediarender service
    ansible.builtin.systemd:
      name: gmediarender
      state: restarted
      enabled: yes
      daemon_reload: yes